name: treefuckers
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  
  
  file_picker: ^5.2.2
  flex_color_scheme: ^5.1.0
  flutter: 
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  freezed: ^2.2.1
  hooks_riverpod: ^2.1.1
  
  http: ^0.13.5
  lan_scanner: ^3.5.0
  numberpicker: ^2.1.1
  shared_preferences: ^2.0.15
  
  
  

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter
  rename: ^2.0.1

flutter: 
  uses-material-design: true

